resctrl: fix move from x86 to common resctrl
Commit 2be5e738e86 ("x86/resctrl: Move CLOSID/RMID matching and
setting to use helpers") introduced compilation regression on x86
by overwriting task argument in resctrl_sched_in, added by upstream
7ec0076b424e ("x86/resctl: fix scheduler confusion with 'current'")

Fixes compilation error:
arch/x86/include/asm/resctrl.h:184:36: error: 'task' undeclared (first use in this function)
	__resctrl_sched_in(task);
..

Fixes: 2be5e738e86 ("x86/resctrl: Move CLOSID/RMID matching and setting to use helpers")

Change-Id: I3224a755d273a46ae1ff463c27aef8179b3b635f
Signed-off-by: Wladislav Wiebe <wladislav.wiebe@nokia.com>
Signed-off-by: Amit Singh Tomar <amitsinght@marvell.com>
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/kernel/linux/+/118515
Reviewed-by: Sunil Kovvuri Goutham <sgoutham@marvell.com>
Tested-by: Sunil Kovvuri Goutham <sgoutham@marvell.com>