mrvl-loki: do not enable driver per default
There are no proper Kconfig dependencies for that driver
and it should not compile per default for all platforms.

Fixes arm32 compilation:
drivers/misc/mrvl-loki.c:79:15: error: implicit declaration of function 'readq_relaxed';
            val = readq_relaxed(ml->psm_gpint + PSM_GPINT0_SUM_W1C) & CPRI_INT_MASK;
                  ^~~~~~~~~~~~~
..

Fixes: b6b2e28490ae ("misc: mrvl-loki: Add driver to handle GPINT0 interrupt")
Change-Id: I9502eb2ee66a48a4aec47b3cb1f048357efd90f8
Signed-off-by: Wladislav Wiebe <wladislav.wiebe@nokia.com>
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/kernel/linux/+/118241
Reviewed-by: Sunil Kovvuri Goutham <sgoutham@marvell.com>
Tested-by: Sunil Kovvuri Goutham <sgoutham@marvell.com>