fs/resctrl: fix argument for devnode callback.
callback that provide devtmpfs (through @devnode) expects first argument to be
"struct device *dev", and in case of mismatch, it triggers a compilation error.

For instance, pseudo_lock_devnode callback uses "const struct devce *dev" as
first argument that results in following compilation error:

error: assignment to ‘char * (*)(struct device *, umode_t *)’
{aka ‘char * (*)(struct device *, short unsigned int *)’} from incompatible
pointer type ‘char * (*)(const struct device *, umode_t *)’
{aka ‘char * (*)(const struct device *, short unsigned int *)’}
[-Werror=incompatible-pointer-types]

Fix it, by using first argument as expected by @devnode callback.

Signed-off-by: Amit Singh Tomar <amitsinght@marvell.com>